### ISSUE TITLE
Populate the delete date in the EK_* tables

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/aiw-i2b2-etl#3]
This functionality will set the delete date column with the value of Proposition.getDeleteDate().

**Comment by arpost** [comment]
Depends on #1

**Comment by arpost** [comment]
Please add delete date values to the test data and modify the tests to check that the EK_\* tables are populated correctly.

**Comment by akalsan** [comment]
I have changed the aiw-i2b2-etl code to populate this column in the temp tables. To start with the tests, i changed the testdata to have a delete date in encounter table. The test data is populated into the h2 database fine but it is not populated into the temp tables. I put breakpoints into visitdimensionhandler class to see what proposition.getdate returns and it still returns null. Do you want me to push the code to my origin so that you take a look at it or do you want me to look into how proposition.getdeletedate is being populated from the source data(possibly the entity specs?) or am i doing something wrong here? i still need to change the test data for patient table and events. But i wanted to start with one and make sure that is going through.

**Comment by akalsan** [comment]
FYI- the datasource backend edits need to happen so that the delete_data field from the source reaches the temp tables.
